### ISSUE TITLE
How to, No redme

### ISSUE THREAD

**Issue by 00itsm00** [hemantapkh/seedrcc#1]
Hi Team,

There's no how to or readme. Kindly provide one to test it. Thanks.

**Comment by hemantapkh** [comment]
Just started working on this project. Will do it in few days :)

**Comment by 00itsm00** [comment]
Okay great. Thanks.

**Comment by hemantapkh** [comment]
Sorry for the delay, the documentation is now available at https://seedrcc.readthedocs.io/. Also, see the [README](https://github.com/hemantapkh/seedrcc/blob/main/README.md) file for more information.
