### ISSUE TITLE
How to download using seedrcc api?

### ISSUE THREAD

**Issue by bitcoinmeetups** [hemantapkh/seedrcc#3]
Hi,

I'm BM, a very nice and polite guy.

How to download using seedrcc api? I can add torrents but is there a way to download them too?

**Comment by hemantapkh** [comment]
Hi, please use [createArchive](https://seedrcc.readthedocs.io/en/latest/seedrcc.html#seedrcc.seedr.Seedr.createArchive) and [fetchFile](https://seedrcc.readthedocs.io/en/latest/seedrcc.html#seedrcc.seedr.Seedr.fetchFile) method to download a folder or file. 

Folder download have some issue from seedr itself. https://github.com/hemantapkh/seedrcc/issues/2
